#pragma once

namespace ElecCirSim
{
	enum ComponentTypes
	{
		WIRE_COMPONENT,
		DC_VOLTAGE_SOURCE_COMPONENT,
		AC_VOLTAGE_SOURCE_COMPONENT,
		GROUND_COMPONENT,
		POWER_SWITCH_COMPONENT,
		RESISTOR_COMPONENT,
		CAPACITOR_COMPONENT,
		INDUCTOR_COMPONENT,
		POTENTIOMETER_COMPONENT,
		TRANSFORMER_COMPONENT,
		DIODE_COMPONENT,
		ZENER_DIODE_COMPONENT,
		LED_COMPONENT,
		NPN_TRANSISTOR_COMPONENT,
		PNP_TRANSISTOR_COMPONENT,
		N_MOSFET_COMPONENT,
		P_MOSFET_COMPONENT,
		NOT_GATE_COMPONENT,
		AND_GATE_COMPONENT,
		OR_GATE_COMPONENT,
		NAND_GATE_COMPONENT,
		NOR_GATE_COMPONENT,
	};
}