#pragma once

namespace ElecCirSim
{
	enum TerminalTypes
	{
		FIRST_TERMINAL,
		SECOND_TERMINAL,
		WIPER_TERMINAL,
		LIVE_TERMINAL,
		NEUTRAL_TERMINAL,
		GROUND_TERMINAL,
		COLLECTOR_TERMINAL,
		BASE_TERMINAL,
		EMITTER_TERMINAL,
		GATE_TERMINAL,
		BODY_TERMINAL,
		SOURCE_TERMINAL,
		DRAIN_TERMINAL,
		GATE_INPUT_TERMINAL,
		GATE_OUTPUT_TERMINAL
	};
}